### ISSUE TITLE
"Me" mob is too big

### ISSUE THREAD

**Issue by niraqw** [noobanidus/miniatures#13]
The "Me" mob has the same sized model as the "MaxiMe". The hitbox seems to be the slightly larger/taller than a normal player.

Minecraft 1.18.2
Forge 40.0.44

Mod List:
miniatures-1.18.2-0.2.6.21
shetiphiancore-1.18-3.10.7

**Comment by noobanidus** [comment]
This should be resolved in the most recent release, `0.2.6.22`! Please let me know if you have any other issues.

**Comment by pantsguyapp** [comment]
Can you guys release a hotfix for this issue in 1.16?
