### ISSUE TITLE
Normal sized and giant mini me have large arms

### ISSUE THREAD

**Issue by pantsguyapp** [noobanidus/miniatures#17]
They should have slimmer arms, like a standard player model.

In 1.16 versions, pls hotfix this one.

**Comment by noobanidus** [comment]
a) Please consider phrasing your requests to be less demanding. "Please hotfix" is not acceptable.
b) I don't currently have a 1.16.5 development environment of Miniatures around, but from what I can tell, they are using the geometry of the player model. The size of the arms depends on whether it's an Alex or Steve skin.
