### ISSUE TITLE
Suggestion: Arms Overlapping

### ISSUE THREAD

**Issue by ogr3magi** [noobanidus/miniatures#3]
I want to start with: This mod is fantastic! Thank you for making it for us!

The arms seem to be set inside the body slightly causing an odd pixel flipflop during the idle animation. Can the arms be moved out slightly to reduce that crossover?

<img width="546" alt="clipping" src="https://user-images.githubusercontent.com/48671266/124702278-1e64b100-debe-11eb-8be1-c252572c09a2.PNG">

**Comment by noobanidus** [comment]
I'm not sure if there's much I can do about this, as it's the standard vanilla player model.
