### ISSUE TITLE
Adopt AI blacklist tag from MineColonies

### ISSUE THREAD

**Issue by ChosenArchitect** [noobanidus/miniatures#6]
Mod Ver: miniatures-1.16.5-0.0.2.12

Issue: Iron Golems Try and Kill Miniatures. 
![2021-08-17_10 02 09](https://user-images.githubusercontent.com/35053440/129751603-cfbe9295-0707-49fb-a54a-7090092eafbc.png)

**Comment by noobanidus** [comment]
Confer: https://github.com/ldtteam/minecolonies/pull/7611
