### ISSUE TITLE
Using Miniatures with TwitchSpawn!

### ISSUE THREAD

**Issue by Shindur** [noobanidus/miniatures#7]
Twitch spawn command: 

```
EXECUTE 
 %/summon miniatures:minime ~ ~ ~ {CustomName:"\"${actor}\"",CustomNameVisible:1,owner:"${actor}"}%
 %/summon firework_rocket ~ ~1 ~10 {LifeTime:20,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Trail:1,Colors:[I;4312372],FadeColors:[I;11743532]}],Flight:1}}}}%
 DISPLAYING %[{text:"and summoned a mini me in your likeness", color:"white"}]%
 ON Twitch Channel Point Reward
 WITH title IS %Mini Me!%
```

If I use the summon command as such: /summon miniatures:minime ~ ~ ~ {CustomName:"\"Shindur\"",CustomNameVisible:1,Owner:"\"Shindur\""} or even without quotes or without the extra ones and \'s the custom skin doesn't pop up.

However if I use a nametag with that person's name on it then the skin appears. Just trying to set it up so when a minime is spawned then the skin appears. Any help as to how I may be doing it wrong would be appreciated too!

**Comment by noobanidus** [comment]
Hi there!

All of the tags are case sensitive and you *shouldn't* need to double-quote them. Try out if `/summon miniatures:minime ~ ~ ~ {owner:"Shindur"}` works for you!

**Comment by Shindur** [comment]
Hey so I tried it out and while running it the way you had it laid out works fine, I'm trying to use it with TwitchSpawn, and I'm not sure if it's something on their end, but when I tell that mod to run the command it doesn't spawn with the custom skin if I set the owner to $actor which is what they use for grabbing the name of whoever donated/subbed/gave bits/etc.

**Comment by noobanidus** [comment]
Oh, that's interesting. I believe FibroWolf uses TwitchSpawn -- he's not on my Discord, but I'm pretty sure he's got them working with that. You might try finding his Discord to ask him questions about it?

Unfortunately, the only experience I've had with them is with CCI. 

If you do have a solution, I might add a specific page to the wiki about it.

**Comment by Shindur** [comment]
Just so I have the right person, it's this FibroWolf, yeah? https://www.twitch.tv/fibrowolf
If so when he's live next I'll ask him and report back :)

**Comment by noobanidus** [comment]
Yep, that FibroWolf -- I believe he has a discord you could potentially join and ask questions in as well. 

Sorry that I can't be of more help! I know he did have difficulties getting them to work initially, but ended up getting them to work after all.

EDIT: If you do find out the correct way to do it, I'd love to be able to pin this issue as a "How to use Miniatures with TwitchSpawn".

**Comment by Shindur** [comment]
Got in touch with FibroWolf. He says he got it to work, but inconsistently, so he removed the mod. Though this was back in All The Mods 3 he says, so not sure how much has changed since then. 

Is it possible you could look into why it's not working correctly? You mentioned that owner had to be lower case as it was case sensitive, are you using your own override of MC Owner NBT tag?

**Comment by Shindur** [comment]
Ok, scratch that.. Fibro provided me the code he used, I tested it out.. and it works! Here's the code snippet for use in TwitchSpawn that worked for him and myself, modified a bit to have custom names shown above the head.

EXECUTE 
 %/summon miniatures:minime ~ ~ ~ {CustomName:"\"${actor}\"",CustomNameVisible:1,owner:"${actor}"}%
 %/summon firework_rocket ~ ~1 ~10 {LifeTime:20,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Trail:1,Colors:[I;4312372],FadeColors:[I;11743532]}],Flight:1}}}}%
 DISPLAYING %[{text:"and summoned a mini me in your likeness", color:"white"}]%
 ON Twitch Channel Point Reward
 WITH title IS %Mini Me!%

He pointed out that my issue was when using the EXECUTE function for TS that I had an extra set of % % around a bit of my code.
